replicaCount: 1

global:
  domain: "k8slab.int"

orchestrator:
  name: orc8r

image:
  registryUrl: registry.k8slab.int/tcpdump
  orchestratorImageName: orchestrator:0.1.0
  tcpdumpImageName: tcpdump:0.1.0

  #pullPolicy: IfNotPresent
  pullPolicy: Always
  tag: ""

imagePullSecret: tcpdump-orchestrator

istio:
  enabled: true