apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-job-template
data:
  job_template.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: ${JOB_NAME}
      labels:
        app: tcpdump
        tcpdump-target-pod: ${POD_NAME}
        tcpdump-target-namespace: ${TARGET_NAMESPACE}
    spec:
      ttlSecondsAfterFinished: 30
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
            app: tcpdump
            tcpdump-target-pod: ${POD_NAME}
            tcpdump-target-namespace: ${TARGET_NAMESPACE}
        spec:
          nodeName: ${NODE_NAME}
          hostPID: true
          imagePullSecrets:
            - name: {{ .Values.imagePullSecret }}
          containers:
          - name: crictl-container
            image: {{ .Values.image.registryUrl }}/{{ .Values.image.tcpdumpImageName }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
            - bash
            - -x
            - /opt/exec.sh
            env:
            - name: POD_NAME
              value: "${POD_NAME}"
            - name: NAMESPACE
              value: "${TARGET_NAMESPACE}"
            - name: CONDITION
              value: "-i any -s 0"
            - name: TIMEOUT
              value: "900"
            securityContext:
              privileged: true
            volumeMounts:
            - name: containerd-sock
              mountPath: /var/run/containerd/containerd.sock
            - name: crictl-config
              mountPath: /etc/crictl.yaml
              readOnly: true
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: containerd-sock
            hostPath:
              path: /var/run/containerd/containerd.sock
              type: Socket
          - name: crictl-config
            hostPath:
              path: /etc/crictl.yaml
              type: File
          - name: host-proc
            hostPath:
              path: /proc
              type: Directory
