---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-orchestrator  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-orchestrator  
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-orchestrator  
    spec:      
      serviceAccountName: {{ .Release.Name }}-service-account
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}      
      containers:
        - name: app
          image: {{ .Values.image.registryUrl }}/{{ .Values.image.orchestratorImageName }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: traces
              mountPath: /app/traces
            - name: job-template
              mountPath: /app/templates/job_template.yaml
              subPath: job_template.yaml
              readOnly: true
      volumes:
        - name: traces
          emptyDir: {}
        - name: job-template
          configMap:
            name: {{ .Release.Name }}-job-template          
