---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-orchestrator
spec:
  selector:
    app: {{ .Release.Name }}-orchestrator
  {{- if .Values.istio.enabled }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
