---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-orchestrator
spec:
  selector:
    app: {{ .Release.Name }}-orchestrator
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
