---
{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-orchestrator-vs
spec:
  hosts:
  - {{ .Values.orchestrator.name }}.{{ .Release.Namespace }}.{{ .Values.global.domain }}  
  gateways:
  - {{ .Release.Name }}-orchestrator-gw
  http:
  - match:
    - uri:
        prefix: /  
    route:
    - destination:
        host: {{ .Release.Name }}-orchestrator
        port:
          number: 80
{{- end }}          